/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package files.numberfinder;
import java.util.*;

public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public int vl;
    public int count = 0;
    public Main() {
        setTitle("Number Finder");
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        
        Random random = new Random();
        for(int i = 1; i < 9; i++){
          vl = random.nextInt(i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        lbl7 = new javax.swing.JLabel();
        lbl8 = new javax.swing.JLabel();
        lbl9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        val = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 253));

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 253));

        lbl1.setFont(new java.awt.Font("Arial", 1, 100)); // NOI18N
        lbl1.setText("1");
        lbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl1MouseClicked(evt);
            }
        });

        lbl2.setFont(new java.awt.Font("Arial", 1, 100)); // NOI18N
        lbl2.setText("2");
        lbl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl2MouseClicked(evt);
            }
        });

        lbl3.setFont(new java.awt.Font("Arial", 1, 100)); // NOI18N
        lbl3.setText("3");
        lbl3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl3MouseClicked(evt);
            }
        });

        lbl4.setFont(new java.awt.Font("Arial", 1, 100)); // NOI18N
        lbl4.setText("4");
        lbl4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl4MouseClicked(evt);
            }
        });

        lbl5.setFont(new java.awt.Font("Arial", 1, 100)); // NOI18N
        lbl5.setText("5");
        lbl5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl5MouseClicked(evt);
            }
        });

        lbl6.setFont(new java.awt.Font("Arial", 1, 100)); // NOI18N
        lbl6.setText("6");
        lbl6.setToolTipText("");
        lbl6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl6MouseClicked(evt);
            }
        });

        lbl7.setFont(new java.awt.Font("Arial", 1, 100)); // NOI18N
        lbl7.setText("7");
        lbl7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl7MouseClicked(evt);
            }
        });

        lbl8.setFont(new java.awt.Font("Arial", 1, 100)); // NOI18N
        lbl8.setText("8");
        lbl8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl8MouseClicked(evt);
            }
        });

        lbl9.setFont(new java.awt.Font("Arial", 1, 100)); // NOI18N
        lbl9.setText("9");
        lbl9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl9MouseClicked(evt);
            }
        });

        val.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        val.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        val.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(val, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(val)
                .addGap(0, 54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(lbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl2)
                .addGap(18, 18, 18)
                .addComponent(lbl3)
                .addGap(11, 11, 11)
                .addComponent(lbl4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl5)
                .addGap(13, 13, 13)
                .addComponent(lbl6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl9)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl2)
                        .addComponent(lbl1)
                        .addComponent(lbl3)
                        .addComponent(lbl4))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl6)
                        .addComponent(lbl5)
                        .addComponent(lbl7)
                        .addComponent(lbl8)
                        .addComponent(lbl9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        
    public void disable(){
      lbl1.setEnabled(false);
      lbl2.setEnabled(false);
      lbl3.setEnabled(false);
      lbl4.setEnabled(false);
      lbl5.setEnabled(false);
      lbl6.setEnabled(false);
      lbl7.setEnabled(false);
      lbl8.setEnabled(false);
      lbl9.setEnabled(false);
    }
    private void lbl1MouseClicked(java.awt.event.MouseEvent evt) {                                  
        if(vl == 1){
         val.setText("Correct you got it in  "+count+" attempts !");
         disable();
         lbl1.setEnabled(true);
        }else{
         lbl1.setEnabled(false);
         val.setText("Incorect try again!");
         count++;
        }
    }                                 

    private void lbl2MouseClicked(java.awt.event.MouseEvent evt) {                                  
        if(vl == 2){
          
         val.setText("Correct you got it in  "+count+" attempts !");
         disable();
         lbl2.setEnabled(true);
        }else{
         lbl2.setEnabled(false);
         val.setText("Incorect try again!");
         count++;
        }
    }                                 

    private void lbl3MouseClicked(java.awt.event.MouseEvent evt) {                                  
        if(vl == 3){
          
         val.setText("Correct you got it in  "+count+" attempts !");
         disable();
         lbl3.setEnabled(true);
        }else{
         lbl3.setEnabled(false);
         val.setText("Incorect try again!");
         count++;
        }
    }                                 

    private void lbl4MouseClicked(java.awt.event.MouseEvent evt) {                                  
        if(vl == 4){
         
         val.setText("Correct you got it in  "+count+" attempts !");
         disable();
         lbl4.setEnabled(true);
        }else{
         lbl4.setEnabled(false);
         val.setText("Incorect try again!");
         count++;
        }
    }                                 

    private void lbl5MouseClicked(java.awt.event.MouseEvent evt) {                                  
        if(vl == 5){
          
         val.setText("Correct you got it in  "+count+" attempts !");
         disable();
         lbl5.setEnabled(true);
        }else{
         lbl5.setEnabled(false);
         val.setText("Incorect try again!");
         count++;
        }
    }                                 

    private void lbl6MouseClicked(java.awt.event.MouseEvent evt) {                                  
        if(vl == 6){
         
         val.setText("Correct you got it in  "+count+" attempts !");
         disable();
         lbl6.setEnabled(true);
        }else{
         lbl6.setEnabled(false);
         val.setText("Incorect try again!");
         count++;
        }
    }                                 

    private void lbl7MouseClicked(java.awt.event.MouseEvent evt) {                                  
       if(vl == 7){
         val.setText("Correct you got it in  "+count+" attempts !");
         disable();
         lbl7.setEnabled(true);
        }else{
         lbl7.setEnabled(false);
         val.setText("Incorect try again!");
         count++;
        }
    }                                 

    private void lbl8MouseClicked(java.awt.event.MouseEvent evt) {                                  
       if(vl == 8){
          
         val.setText("Correct you got it in  "+count+" attempts !");
         disable();
         lbl8.setEnabled(true);
        }else{
         lbl8.setEnabled(false);
         val.setText("Incorect try again!");
         count++;
        }
    }                                 

    private void lbl9MouseClicked(java.awt.event.MouseEvent evt) {                                  
        if(vl == 9){
          
         val.setText("Correct you got it in  "+count+" attempts !");
         disable();
         lbl9.setEnabled(true);
        }else{
         lbl9.setEnabled(false);
         val.setText("Incorect try again!");
         count++;
        }
    }                                 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl9;
    private javax.swing.JLabel val;
    // End of variables declaration                   
}
